#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 /root/oled_status.py
    procd_set_param respawn 3600 5 5
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    procd_kill oled
}

restart() {
    stop
    start
}
